title: "Sourabh K"
description: "Staff Engineer @ LogicMonitor (ex-TCS) — 12 years | Backend • Java • Spring • Microservices"
url: "https://sourabhk-in.github.io"  
baseurl: ""                      
lang: en

# GitHub Pages-compatible remote theme (no local build required)
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Social/User meta
author:
  name: "Sourabh K"
  github: sourabhk-in      
  linkedin: https://www.linkedin.com/in/sourabh-k-00824525/
  email: sourabhk@outlook.in  

# Navigation (optional)
navbar:
  - name: About
    href: "#about"
  # - name: Projects
  #   href: "#projects"
  - name: Skills
    href: "#skills"
  - name: Contact
    href: "#contact"

# Theme tweaks
show_downloads: false
google_analytics: ""   # ← optional: GA ID or leave empty
